apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
 name: cd-gui-demo
description: application deployment pipeline
serialPipeline:
 stages:
 - targetId: cd-gui-target-stage
   profiles: [stage]
 - targetId: cd-gui-target-prod
   profiles: [prod]

---

apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
 name: stage
description: Cloud Run Stage service
run:
 location: projects/_PROJECT_ID/locations/us-central1
---

apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
 name: prod
description: Cloud Run PROD service
run:
 location: projects/_PROJECT_ID/locations/us-central1
