apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: cd-gui-demo
serialPipeline:
  stages:
  - targetId: cd-gui-target-stage
    profiles:
    - cd-gui-target-stage
  - targetId: cd-gui-target-prod
    profiles:
    - cd-gui-target-prod
    strategy:
      canary:
        runtimeConfig:
          cloudRun:
            automaticTrafficControl: true
        canaryDeployment:
          percentages:
          - 10
