apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: service-a-stage
spec:
  template:
    spec:
      containers:
      - image: service-a
        ports: 
        - name: http1
          containerport: 8080
