apiVersion: skaffold/v3alpha1
kind: Config
metadata: 
  name: service-a
profiles:
- name: cd-gui-target-stage
  manifests:
    rawYaml:
    - deploy-stage.yaml
- name: cd-gui-target-prod
  manifests:
    rawYaml:
    - deploy-prod.yaml
deploy:
  cloudrun: {}
